config/routes.rb
Rails.application.routes.draw do

  get '/users/sign_out', to: 'devise/sessions#destroy'

  devise_for :users

  root 'home#home'

  resources :links do
   member do
    put "like", to: "links#upvote"
    put "dislike", to: "links#downvote"
   end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  acts_as_votable
  # validates :title, presence: true
  validates :url, presence: true

  def self.to_csv(options = {})
    desired_columns = ["url"]
    CSV.generate(options) do |csv|
      csv << ["Placement"]
      all.each do |link|
        csv << link.attributes.values_at(*desired_columns)
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  validates_uniqueness_of :username

  attr_accessor :login
  has_many :links
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable,
  :validatable, :authentication_keys => {email: true, login: false}

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    @links = Link.all.order('created_at DESC')
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def new
    @link = Link.new
  end

  def index
    @link = Link.all

    respond_to do |format|
      format.html
      format.csv { send_data @link.to_csv, :filename => 'Placements.csv' }
      format.xls
    end
  end


  def create
    @user = current_user
    @link = @user.links.new(link_params)
    if @link.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])

    if @link.update(link_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @link = Link.find(params[:id])

    if @link.user == current_user
      @link.destroy
      redirect_to root_path
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_back fallback_location: root_path
  end

  private
  def link_params
    params.require(:link).permit(:title, :url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/home/home.html.erb
<section id="content">
  <ol id="links-list">
    <% @links.each do |link| %>
    <li>
      <span class="link"><%= link_to link.url, link.url %></span>
      <% if link.user == current_user %>
      <span class="details">
        <%= link_to "edit", edit_link_path(link) %>
        <%= link_to "delete", link_path(link), method: :delete %>
      </span>
      <% end %>
      <p>Posted By
        <%= link_to link.user.username %>
        <%= time_ago_in_words(link.created_at) %>
      </p>
      <div class="btn-group">
        <a class="btn btn-default btn-sm" href="<%= link.url %>" target="_blank">Visit Link</a>

        <%= link_to like_link_path(link), method: :put, style: "padding: 2px; padding-left: 24px" do %>
        <i class="fa fa-thumbs-up"></i>
        <%= link.get_upvotes.size %>
        <% end %>

        <%= link_to dislike_link_path(link), method: :put, style: "padding: 2px" do %>
        <i class="fa fa-thumbs-down"></i>
        <%= link.get_downvotes.size -%>
        <% end %>

      </div>
    </li>
    <% end %>
  </ol>
</section>

app/views/layouts/_header.html.slim
header.navbar
  ul.links
    li = link_to "Detention", root_path
    li = link_to "GDN placement exclusion list aggregator", root_path
  ul.auth
    li
      = link_to links_path(format: "csv") do |l|
        i.fa.fa-download
        span.exp-csv Export all placements
    - if user_signed_in?
      li = link_to "Submit Link", new_link_path
      li = link_to 'Edit profile', edit_user_registration_path
      li = link_to 'Logout', destroy_user_session_path, :method => :delete
    - else
      li = link_to 'Login', new_user_session_path
      li = link_to 'Signup', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Detention
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    div#wrapper
      = render 'layouts/header'
      = yield

app/views/links/_form.html.slim
= simple_form_for @link do |f|
  = f.input :url
  = f.button :submit

app/views/links/edit.html.slim
h1 Edit a Link

= render 'form'

app/views/links/new.html.slim
h1 Submit a Link

= render 'form'